### ISSUE TITLE
Рисовка существ

### ISSUE THREAD

**Issue by tichdog** [tichdog/intensiveSpring#26]
По данному контуру нарисовать существ (червя, кузнечика, гидру). 
Размеры примерны, и будут зависеть от контура. Но они не должны быть маленькими, что бы не было видно пиксели.
размеры червя 700 высота и 3000 ширина 
размеры кузнечика 1000 высота 2700 ширина
размеры гидры 1800 высота 1400 ширина

Сделать до 01.04.2024

**Comment by Darvanna** [comment]
![Без названия195_20240402040600](https://github.com/tichdog/intensiveSpring/assets/138600702/54efea13-cb93-432d-84a1-7e6b3d9116e1)
![Без названия196_20240402041803](https://github.com/tichdog/intensiveSpring/assets/138600702/f008ca6b-1cd1-4bff-b836-100738c221af)
![1712041505962](https://github.com/tichdog/intensiveSpring/assets/138600702/474effd6-5bb4-4eea-a67b-f46109fae7b5)

**Comment by Darvanna** [comment]
![Без названия188_20240401191107](https://github.com/tichdog/intensiveSpring/assets/138600702/780de822-6866-4e83-a6ed-92de33fc8c16)
![Без названия182_20240401143505](https://github.com/tichdog/intensiveSpring/assets/138600702/1440b504-1fc5-4bec-927f-950bfd51aeda)
![Без названия182_20240401140402](https://github.com/tichdog/intensiveSpring/assets/138600702/f42fd859-c04e-431a-bdb7-c80d8af98cea)
